fixed response if user isn't found
JujaLabs/users pull request #48
Opened 2017-07-16 18:46 UTC by atem085

connect #40

2017-07-16 19:00 UTC, NikolayNN commented on src/main/java/juja/microservices/users/service/UserService.java
> +            throw new UserException("User" + request.getSlackNames() + "found by your request!");
I think you missed "not" in the exception message

2017-07-16 19:02 UTC, atem085 commented on src/main/java/juja/microservices/users/service/UserService.java
> +            throw new UserException("User" + request.getSlackNames() + "found by your request!");
Done

2017-07-16 19:12 UTC, NikolayNN commented on src/main/java/juja/microservices/users/service/UserService.java
> +            throw new UserException("User" + request.getSlackNames() + "isn't found by your request!");
And I think you should use Past Simple Passive, instead Present Simple Passive :)
for example: Users weren't found.

2017-07-16 19:15 UTC, atem085 commented on src/main/java/juja/microservices/users/service/UserService.java
> +            throw new UserException("User" + request.getSlackNames() + "isn't found by your request!");
Done :)

2017-07-17 06:22 UTC, VadimDyachenko reviewed
Оставил комментарий.

2017-07-17 06:22 UTC, VadimDyachenko commented on src/main/java/juja/microservices/users/service/UserService.java
> +            logger.warn("Users" + request.getSlackNames() + "isn't found. Received empty list from repository.");
Некорректное формирование тела логгера. Используй вместо '+ request.getSlackNames() +'  фигурные скобки {}, а после сообщения через запятую указываешь нужные параметры:
logger.warn("Users {} isn't found. Received empty list from repository.", request.getSlackNames());

2017-07-17 17:55 UTC, atem085 commented on src/main/java/juja/microservices/users/service/UserService.java
> +            logger.warn("Users" + request.getSlackNames() + "isn't found. Received empty list from repository.");
Исправил

2017-07-18 20:54 UTC, OlgaKulikova requested changes

2017-07-18 20:54 UTC, OlgaKulikova commented on src/main/java/juja/microservices/users/service/UserService.java
> +        } catch (NullPointerException e) {
Honestly, I don't like it. Noone catches NullPointerException. If you want to use feature of Java8, look at the Optional class as solution. Or check `if null` with old plain method.

2017-08-07 19:40 UTC, OlgaKulikova approved these changes

2017-08-07 19:40 UTC, merged